# Generated by Django 3.2.4 on 2021-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('adress', models.CharField(max_length=150)),
                ('typePage', models.CharField(max_length=10)),
            ],
        ),
    ]
